app:
  port: 10005

mongo:
  uri: mongodb://192.168.10.181:27017

engine:
  platform: huobi
  proxy_url: http://127.0.0.1:10809
  ws_url: wss://api.huobi.pro/ws
  http_url: https://api.huobi.pro
  symbols:
    - btcusdt
  periods:
    - 1min